### PR TITLE
Prepare the CLI to be part of the asciidoctor meta package

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by Mogztter** [comment]
What do you think about it @mojavelinux  ?
`asciidoctorjs` does not read very well and since we've decided to integrate the CLI in the meta package named `asciidoctor`, I think it makes sense:

```
$ npm i asciidoctor
$ asciidoctor README.adoc
```

**Comment by mojavelinux** [comment]
This one is tricky because it's entirely possible that it shadows the Ruby CLI. But if we're willing to take that risk...though the name clash does cause me some heartburn.

**Comment by Mogztter** [comment]
> But if we're willing to take that risk...though the name clash does cause me some heartburn.

I'm also torn between the two... but at the same time that's already the case with system and gem:

```
sudo apt-get install asciidoctor
```
```
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
asciidoctor est déjà la version la plus récente (1.5.5-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```
```
$ which asciidoctor          
/home/guillaume/.rvm/gems/ruby-2.3.0/bin/asciidoctor
```

```
$ /usr/bin/asciidoctor --version
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```
```
$ asciidoctor --version     
Asciidoctor 1.5.8 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by oncletom** [comment]
In the past, I unententionally used `asciidoctor` as the CLI name, thinking it was the JS runtime except it was calling the Ruby one.

I rarely faced the case when an npm executable had a different name than its package name. And I was confused the few times it happened.

It's going to be tricky when both Ruby and JS Asciidoctor are installed globally at the same time. I don't know if that can be detected by the CLI and a warning eventually issued.

**Comment by Mogztter** [comment]
> In the past, I unententionally used asciidoctor as the CLI name, thinking I was calling the JS runtime, except it was calling the Ruby one.
I rarely faced the case when an npm executable had a different name than its package name. And I was confused the few times it happened.

Exactly, that's what I'm trying to avoid.

> It's going to be tricky when both Ruby and JS Asciidoctor are installed globally at the same time. I don't know if that can be detected by the CLI and a warning eventually issued.

Not sure about this one... it really comes down to how the `PATH` is configured. Maybe we could check if `asciidoctor` exists more than once in the `PATH` (for reference: https://github.com/springernature/hasbin). In addition, we should also check if the binaries are the same or not.
I believe we could run this check at install time ? (I've never done that before but I think it's possible right ?)

Obviously `asciidoctor --version` will output `Asciidoctor.js 2.0.0` and hopefully it will be pretty rare to install both the Ruby runtime and the JavaScript runtime.

**Comment by Mogztter** [comment]
I think we should go forward with this change, it's the last issue standing before the first 2.0.0 release.

**Comment by mojavelinux** [comment]
If Asciidoctor.js were ever packaged for Fedora, it's likely the binary
name asciidoctor can't be reused. But that type of renaming is typical in
Fedora, so users expect it. For our purposes, I think we can overload the
name, so go for it.

It might be a good idea to add asciidoctorjs as an alias, both for
historical reasons / compatibility, and because it would keep the door open
for PATH ordering to use both. That seems like the perfect compromise to me.

**Comment by mojavelinux** [comment]
And by "add the alias", I mean retain it as an alias.

**Pull request merged**
