### PR TITLE
resolves #2 enable header/footer by default; add option to suppress

### LINKED ISSUE #2: Add option -s to control header_footer option value
It appears that the CLI generates an embeddable document by default. I think this should be changed so that it generates a full document by default (like it's counterpart, the `asciidoctor` command). The option `-s` should then be added to allow the user to control this behavior.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Note that this PR depends on #4 being merged.

**Comment by mojavelinux** [comment]
\o/

**Comment by mojavelinux** [comment]
Now the `asciidoctorjs` cli is a force to be reckoned with!

**Comment by Mogztter** [comment]
Yes!
Through I have a strange behavior with this document:

```
:toc: right

# Documentation

Here is some text.


image::architecture.png[]

include::architecture.adoc[leveloffset=+1]

## Next header
## Header
## Header
## Header
```

With the Grunt plugin this is working but with `asciidoctorjs` cli I got `Unresolved directive in <stdin> - include::architecture.adoc[leveloffset=+1] Next header Header Header Header`. Note that Next header, Header are not rendered properly but inlined after the error message.

If I add an extra empty line between `include::architecture.adoc[leveloffset=+1]` and `## Next header` then this is working...

**Comment by mojavelinux** [comment]
Looks to me like an endline copy-paste problem. It worked okay when I copied it, so maybe just a lost in translation problem? I'd type it from scratch to be sure.

**Comment by Mogztter** [comment]
Yes that was I though but I can't explain why the exact same document is working with the Grunt plugin and not with the asciidoctorjs command line... maybe a default encoding somewhere...

**Comment by mojavelinux** [comment]
That's always a tough question :)

**Comment by mojavelinux** [comment]
The file is being read using a different function, so that's a possibility. In the Grunt plugin, it seems to be delegating to Grunt. Not sure if that reads at UTF-8.

**Comment by Mogztter** [comment]
I got the same behavior with the Chrome and Firefox extension... it's like the Grunt plugin is ignoring the unresolved include

**Comment by mojavelinux** [comment]
Hmmm. Maybe add a test for that case in the Grunt plugin since it seems there is a test directory.

**Comment by Mogztter** [comment]
Yes I will add a test for both asciidoctor-cli.js and Grunt plugin.

**Comment by Mogztter** [comment]
@mojavelinux Here is the failing test on asciidoctor-cli.js: https://github.com/Mogztter/asciidoctor-cli.js/tree/fail-unresolved-include

And the working test on asciidoctor-grunt-plugin: https://github.com/asciidoctor/asciidoctor-grunt-plugin/pull/8/files

The source file is `unresolved_include.adoc` and the result should handle gracefully unresolved include. To run the test `npm install && grunt`.

**Comment by mojavelinux** [comment]
Thanks! I'll take a look as soon as I get a chance. Hopefully we can get to the bottom of it.

**Comment by mojavelinux** [comment]
I think what we're looking at here is multi-faceted. The tests in grunt pass because its using Asciidoctor.js 1.5.0 and, for some reason in that version, it either a) resolves the include successfully or b) silently drops the line if the include is not resolved. When I switch to Asciidoctor.js 1.5.1, then I start seeing different behavior. When the include is not resolved, it swallows the ensuing line. This is more consistent with what you are seeing in the asciidoctor-cli.js tests.

In the end, I think the version of Asciidoctor.js was confusing us and, in fact, we have a new problem in the current version of Asciidoctor.js when an include is not resolved.

What I haven't been able to figure out yet is why it is swallowing the line after the unresolved include.

**Comment by mojavelinux** [comment]
The swallowing of the line turns out to be a bug in Asciidoctor core. We just never see that bug because it happens only when the IO fails in the way that it fails in Asciidoctor.js. The file has to be unreadable (passing by the file exists check).

**Comment by mojavelinux** [comment]
So basically, none of this has to do with Asciidoctor.js. The test case in Grunt is hitting the problem that we aren't reading files that begin with `file://`, which is a known issue. I actually don't think that the Grunt task should be forcefully setting the base_dir that way because that is causing problems.

**Comment by mojavelinux** [comment]
Reported as https://github.com/asciidoctor/asciidoctor/issues/1602

**Pull request merged**
